[[redirects]]
  from = "/cloud/*"
  to = "https://:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "https://home-github.cloudlinksu.cloudns.org/:splat"
  status = 200
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/jsd/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/cdnjs/ajax/libs/*"
  to = "https://cdnjs.cloudflare.com/ajax/libs/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/goo/ajax/libs/*"
  to = "https://ajax.googleapis.com/ajax/libs/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/goo/fonts/*"
  to = "https://fonts.googleapis.com/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/goo/themes/*"
  to = "https://themes.googleusercontent.com/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/gs/www/*"
  to = "https://www.gstatic.com/ajax/libs/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/gs/fonts/*"
  to = "https://fonts.gstatic.com/:splat"
  status = 200
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/gravatar/*"
  to = "https://secure.gravatar.com/avatar/:splat"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/gith/raw/*"
  to = "https://raw.githubusercontent.com/:splat"
  status = 200
  headers = {X-From = "Netlify"}
