[[redirects]]
  to = "https://:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/*"
  to = "https://homepage.huacloud.eu.org/:splat"
  status = 200
  headers = {X-From = "Netlify"}
